name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Check for Git
        run: |
          if ! command -v git &> /dev/null
          then
              echo "Git not found, installing..."
              sudo yum update -y
              sudo yum install -y git
          else
              echo "Git is already installed."
          fi

      - name: Check for Docker
        run: |
          if ! command -v docker &> /dev/null
          then
              echo "Docker not found, installing..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
          else
              echo "Docker is already installed."
          fi

      - name: Check for Maven
        run: |
          if ! command -v mvn &> /dev/null
          then
              echo "Maven not found, installing..."
              sudo yum update -y
              sudo yum install -y maven
          else
              echo "Maven is already installed."
          fi

      - name: Validate Installation
        run: |
          echo "Validating installation..."
          command -v git
          command -v docker
          command -v mvn

  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: ./mvnw -B package

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./mvnw test

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify JAR file
        run: |
          echo "Verifying JAR file presence..."
          ls -al /home/aiman/Documents/spring-petclinic/target/
          if [ -z "$(find /home/aiman/Documents/spring-petclinic/target/ -name 'spring-petclinic-3.3.0-SNAPSHOT.jar')" ]; then
            echo "JAR file not found in target directory!"
            exit 1
          fi

      - name: Setup SSH
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts || true

      - name: Deploy application
        env:
          DEPLOY_SERVER: 192.168.10.11
          DEPLOY_PORT: 8080
          DEPLOY_USER: aiman
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Deploying application to $DEPLOY_SERVER"
          # Create deployment directory if it doesn't exist
          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER "mkdir -p /home/aiman/deployments/"
          
          # Copy JAR file
          scp -i ~/.ssh/id_rsa /home/aiman/Documents/spring-petclinic/target/spring-petclinic-3.3.0-SNAPSHOT.jar $DEPLOY_USER@$DEPLOY_SERVER:/home/aiman/deployments/
          
          # Ensure the JAR file exists and start the application
          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER "
          if [ -f /home/aiman/deployments/spring-petclinic-3.3.0-SNAPSHOT.jar ]; then 
            nohup java -jar /home/aiman/deployments/spring-petclinic-3.3.0-SNAPSHOT.jar > /dev/null 2>&1 & 
          else 
            echo 'JAR file not found!'; 
            exit 1; 
          fi"
          
          # Clean up private key
          rm -f ~/.ssh/id_rsa
